(function(){
  const M=window.MetaStudio,U=M.utils,$=id=>document.getElementById(id);
  const els={drop:$('dropZone'),input:$('fileInput'),select:$('selectBtn'),status:$('statusBadge'),tabs:$('categoryTabs'),groups:$('metadataGroups'),clean:$('cleanBtn'),review:$('reviewBtn'),list:$('metadataList'),all:$('selectAllBtn'),recommended:$('selectRecommendedBtn'),found:$('summaryFound'),selected:$('summarySelected'),preserved:$('summaryPreserved'),score:$('riskScore'),level:$('riskLevel'),ring:$('riskRing'),riskText:$('riskText'),details:$('viewDetailsBtn'),drawer:$('detailsDrawer'),backdrop:$('drawerBackdrop'),drawerClose:$('drawerClose'),drawerTitle:$('drawerTitle'),reset:$('resetBtn'),verification:$('verification'),cleanName:$('cleanFileName'),before:$('beforeCount'),after:$('afterCount'),note:$('verificationNote'),downloadClean:$('downloadCleanBtn'),downloadZip:$('downloadZipBtn'),toast:$('toast'),profile:$('profileSelect'),profileHelp:$('profileHelp'),hashBefore:$('hashBefore'),hashAfter:$('hashAfter'),fingerprint:$('fingerprint'),verificationTitle:$('verificationTitle')};
  let current=null,originalBytes=null,engine=null,findings=[],cleanBytes=null,afterFindings=[],activeCategory='resumen',originalHash='',cleanHash='';
  const categories=['identidad','ubicacion','dispositivo','software','fechas','ocultos','archivo','tecnico','documento','multimedia'];
  function toast(msg,error=false){els.toast.textContent=msg;els.toast.className='toast show'+(error?' error':'');setTimeout(()=>els.toast.className='toast',3200)}
  M.engineFor=function(name,embedded=false){const ext=U.ext(name);return [M.pdf,M.jpeg,M.png,M.ooxml,M.media,M.archive].find(e=>e&&e.supports(ext))||(embedded?null:M.universal);};
  function normalizeCategory(f){const s=((f.category||'')+' '+(f.key||'')+' '+(f.source||'')).toLowerCase();if(/gps|ubicaci|latitude|longitude|location/.test(s))return'ubicacion';if(/author|autor|creator|artist|company|empresa|organization|usuario|user|email|modified by/.test(s))return'identidad';if(/device|camera|cámara|model|serial|fabricante/.test(s))return'dispositivo';if(/software|producer|application|encoder|codificador|printer|os\b/.test(s))return'software';if(/date|fecha|created|modified|time|timestamp/.test(s))return'fechas';if(/xmp|iptc|exif|hidden|ocult|custom|identifier|uuid|comment|comentario|thumbnail/.test(s))return'ocultos';if(/archivo comprimido|zip|tar|gzip|7z|contenedor|elemento interno/.test(s))return'archivo';if(/multimedia|id3|mp4|mov|wav|audio|video|álbum|artista/.test(s))return'multimedia';if(/técnico|tipo de archivo|tamaño|sha-256/.test(s))return'tecnico';return'documento';}
  function riskText(r){return r==='critico'?'Crítico':r==='alto'?'Alto':r==='medio'?'Medio':r==='bajo'?'Bajo':'Info'}
  function privacyFindings(){return findings.filter(f=>f.kind!=='technical')}
  function technicalFindings(){return findings.filter(f=>f.kind==='technical')}
  function selectedFindings(){return [...els.list.querySelectorAll('input:checked')].map(x=>findings[+x.dataset.i]).filter(Boolean)}
  function syncSummary(){const privacy=privacyFindings(),c=selectedFindings().filter(f=>f.kind!=='technical').length;els.found.textContent=privacy.length;els.selected.textContent=c;els.preserved.textContent=Math.max(0,privacy.length-c);const noPrivacy=!!current&&engine!==M.universal&&privacy.length===0;els.clean.disabled=!current||engine===M.universal||noPrivacy||c===0;els.review.disabled=!current||noPrivacy;els.clean.innerHTML=noPrivacy?'<span>✓</span><span><strong>Sin saneamiento necesario</strong><small>No se han detectado hallazgos de privacidad</small></span>':'<span>✣</span><span><strong>Sanear archivo</strong><small>Crear una copia limpia</small></span>';}
  function applyProfile(){const p=M.profiles[els.profile.value]||M.profiles.standard;els.profileHelp.textContent=p.desc;els.list.querySelectorAll('input').forEach(x=>x.checked=p.pick(findings[+x.dataset.i]));syncSummary();renderGroups();}
  function renderDetails(){
    els.list.innerHTML='';
    const privacy=privacyFindings(),technical=technicalFindings();
    const addTitle=(title,sub)=>{const h=document.createElement('div');h.className='drawer-section-title';h.innerHTML=`<strong>${title}</strong><small>${sub}</small>`;els.list.appendChild(h)};
    addTitle('Hallazgos de privacidad',privacy.length?`${privacy.length} elementos evaluables`:'Sin elementos que requieran saneamiento');
    if(!privacy.length){const empty=document.createElement('div');empty.className='drawer-empty';empty.innerHTML='<strong>✓ No hay metadatos sensibles con contenido significativo.</strong><span>Las propiedades técnicas del archivo se muestran aparte y no forman parte del plan de saneamiento.</span>';els.list.appendChild(empty)}
    privacy.forEach(f=>{const i=findings.indexOf(f),r=M.risk.classify(f),cat=normalizeCategory(f);const row=document.createElement('label');row.className='meta-row';row.dataset.category=cat;row.dataset.kind='privacy';row.innerHTML=`<input type="checkbox" data-i="${i}"><span class="meta-key"><span class="risk-dot ${r}"></span>${U.escapeHtml(f.key)}<small class="meta-source">${U.escapeHtml(f.source||f.category)} · ${riskText(r)}</small>${f.path?`<span class="meta-path">${U.escapeHtml(f.path)}</span>`:''}</span><span class="meta-value" title="${U.escapeHtml(f.value)}">${U.escapeHtml(f.value)}</span>`;els.list.appendChild(row)});
    addTitle('Información técnica','Datos calculados o descriptivos; no son hallazgos de privacidad');
    technical.forEach(f=>{const row=document.createElement('div');row.className='meta-row technical-row';row.dataset.category='tecnico';row.dataset.kind='technical';row.innerHTML=`<span class="technical-mark">i</span><span class="meta-key">${U.escapeHtml(f.key)}<small class="meta-source">${U.escapeHtml(f.source||f.category)} · Información</small></span><span class="meta-value" title="${U.escapeHtml(f.value)}">${U.escapeHtml(f.value)}</span>`;els.list.appendChild(row)});
    els.list.querySelectorAll('input').forEach(x=>x.onchange=()=>{els.profile.value='custom';els.profileHelp.textContent=M.profiles.custom.desc;syncSummary();renderGroups();});applyProfile();filterDrawer();
  }
  function filterDrawer(){[...els.list.querySelectorAll('.meta-row')].forEach(r=>r.hidden=activeCategory!=='resumen'&&r.dataset.category!==activeCategory);els.list.querySelectorAll('.drawer-section-title,.drawer-empty').forEach(x=>x.hidden=activeCategory!=='resumen');els.drawerTitle.textContent=activeCategory==='resumen'?'Plan e información del archivo':`Categoría: ${activeCategory}`;}
  function renderGroups(){const privacy=privacyFindings();if(!privacy.length){els.groups.innerHTML='<div class="placeholder-state success-state"><strong>✓ Sin hallazgos de privacidad</strong><span>No se han detectado metadatos sensibles con contenido significativo. Consulta "Ver detalles" para ver la información técnica del archivo.</span></div>';return;}const defs=[['identidad','◉','Identidad','Autores, usuarios, organizaciones y correos'],['ubicacion','⌖','Ubicación','GPS, coordenadas y referencias geográficas'],['dispositivo','▣','Dispositivo','Cámara, modelo, fabricante e identificadores'],['software','⚙','Software y sistema','Aplicaciones, productores, codificadores y entorno'],['ocultos','◈','Contenido oculto','EXIF, XMP, IPTC, comentarios e identificadores'],['multimedia','▶','Multimedia','Etiquetas y metadatos de audio/vídeo'],['archivo','▤','Archivos comprimidos','Estructura, rutas y metadatos internos'],['documento','≡','Documento','Propiedades descriptivas y de edición']];els.groups.innerHTML='';for(const [cat,icon,title,sub] of defs){const items=privacy.filter(f=>normalizeCategory(f)===cat);if(!items.length)continue;const max=['critico','alto','medio','bajo','info'].find(r=>items.some(f=>M.risk.classify(f)===r))||'info';const sel=items.filter((f)=>{const i=findings.indexOf(f),inp=els.list.querySelector(`input[data-i="${i}"]`);return inp?.checked}).length;const row=document.createElement('div');row.className='group-row';row.innerHTML=`<div class="group-icon">${icon}</div><div class="group-copy"><strong>${title}</strong><small>${sub}</small></div><span class="group-count">${items.length} · ${sel} seleccionados</span><span class="risk-chip ${max==='critico'?'high':max}">${riskText(max)}</span><button class="chev" data-open="${cat}">⌄</button>`;els.groups.appendChild(row)}els.groups.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.open;activateTab(activeCategory);openDrawer()});}
  function renderCounts(){const privacy=privacyFindings(),pairs={Identidad:'identidad',Ubicacion:'ubicacion',Dispositivo:'dispositivo',Software:'software',Ocultos:'ocultos',Archivo:'archivo'};for(const [id,cat] of Object.entries(pairs)){const el=$('count'+id);if(el)el.textContent=privacy.filter(f=>normalizeCategory(f)===cat).length} $('countResumen').textContent=privacy.length;}
  function renderRisk(){const meaningful=findings.filter(f=>f.kind!=='technical'),score=M.risk.score(meaningful),label=M.risk.label(score);els.score.textContent=score;els.ring.style.setProperty('--score',score);els.level.textContent=label;els.riskText.textContent=meaningful.length?`Se han detectado ${meaningful.length} elementos con posible impacto de privacidad.`:'No se han detectado metadatos sensibles mediante los controles compatibles.';els.status.textContent=meaningful.length?'⚠ Hallazgos de privacidad':'✓ Sin hallazgos sensibles';els.status.className='status-badge '+(meaningful.length?'danger':'safe');const cats=[...new Set(meaningful.map(normalizeCategory))].filter(x=>!['tecnico','documento'].includes(x));els.fingerprint.innerHTML=`<b>Huella del archivo</b><span>${cats.length?`Puede revelar: ${cats.slice(0,4).join(', ')}${cats.length>4?'…':''}`:'Sin huella sensible detectable'}</span>`;}
  function activateTab(cat){activeCategory=cat;els.tabs.querySelectorAll('.category-tab').forEach(b=>b.classList.toggle('active',b.dataset.category===cat));filterDrawer();}
  function openDrawer(){if(!current)return;els.backdrop.hidden=false;els.drawer.classList.add('open');els.drawer.setAttribute('aria-hidden','false')}
  function closeDrawer(){els.drawer.classList.remove('open');els.drawer.setAttribute('aria-hidden','true');setTimeout(()=>els.backdrop.hidden=true,180)}
  function render(){els.found.textContent=privacyFindings().length;renderCounts();renderRisk();renderDetails();renderGroups();els.review.disabled=!current||privacyFindings().length===0;els.reset.hidden=false;}
  async function load(file){try{current=file;originalBytes=new Uint8Array(await file.arrayBuffer());engine=M.engineFor(file.name);els.status.textContent='Analizando localmente…';els.status.className='status-badge neutral';els.verification.hidden=true;originalHash=await U.sha256(originalBytes);let specific=await engine.analyze(originalBytes,file);let basic=[];if(engine!==M.universal)basic=await M.universal.analyze(originalBytes,file);findings=[...specific,...basic];render();if(engine===M.universal)toast('Inspección universal completada. No hay saneador específico para este formato.');else toast('Inspección local completada.');}catch(e){console.error(e);toast(e.message||'No se ha podido analizar el archivo.',true);reset();}}
  async function clean(){try{
    const privacy=privacyFindings(),selected=selectedFindings().filter(f=>f.kind!=='technical'),verificationOnly=privacy.length===0;
    if(!verificationOnly&&!selected.length){toast('Selecciona al menos un metadato saneable.',true);return;}
    els.clean.disabled=true;
    if(verificationOnly){cleanBytes=originalBytes.slice();cleanHash=originalHash;afterFindings=[];}else{const out=await engine.clean(originalBytes,selected,current);cleanBytes=out instanceof Uint8Array?out:new Uint8Array(out);cleanHash=await U.sha256(cleanBytes);afterFindings=await engine.analyze(cleanBytes,{name:current.name,type:current.type});}
    const cleanName=verificationOnly?current.name:U.cleanName(current.name);
    if(els.verificationTitle)els.verificationTitle.textContent=verificationOnly?'Archivo verificado sin cambios':'Copia saneada preparada';
    els.cleanName.textContent=verificationOnly?'No ha sido necesario modificar el archivo.':cleanName;
    els.before.textContent=privacy.length;els.after.textContent=afterFindings.filter(f=>f.kind!=='technical').length;els.hashBefore.textContent=originalHash;els.hashAfter.textContent=cleanHash;
    els.note.textContent=verificationOnly?'No se han detectado metadatos sensibles con contenido significativo. Las propiedades técnicas no se consideran hallazgos de privacidad.':(afterFindings.filter(f=>f.kind!=='technical').length?'Quedan hallazgos porque se han conservado o no pueden eliminarse de forma segura con el saneador disponible.':'No se han detectado metadatos sensibles mediante los controles compatibles con este formato.');
    els.verification.hidden=false;
    if(verificationOnly){els.downloadClean.hidden=true;els.downloadZip.innerHTML='<span>↓</span><span><strong>Descargar informe de verificación</strong><small>PDF corporativo con hash y alcance técnico</small></span>';els.downloadZip.onclick=()=>downloadVerificationReport(selected);}else{els.downloadClean.hidden=false;els.downloadClean.onclick=()=>U.download(new Blob([cleanBytes],{type:current.type||'application/octet-stream'}),cleanName);els.downloadZip.innerHTML='<span>↓</span><span><strong>Descargar paquete de evidencias</strong><small>ZIP con archivo saneado + informe PDF</small></span>';els.downloadZip.onclick=()=>downloadEvidence(cleanName,selected);}
    els.verification.scrollIntoView({behavior:'smooth',block:'nearest'});toast(verificationOnly?'Archivo verificado localmente; no requiere saneamiento.':'Copia saneada y verificada localmente.');
  }catch(e){console.error(e);toast(e.message||'No se ha podido completar el proceso.',true);}finally{syncSummary();}}
  function reportData(cleanName,selected){const before=findings.filter(f=>f.kind!=='technical'),after=afterFindings.filter(f=>f.kind!=='technical');return {mode:before.length===0&&selected.length===0?'verification':'sanitization',originalName:current.name,cleanName,originalSize:originalBytes.length,originalHash,cleanHash,date:new Date().toLocaleString('es-ES'),before,after,selected,beforeScore:M.risk.score(before),afterScore:M.risk.score(after),beforeRisk:M.risk.label(M.risk.score(before)),afterRisk:M.risk.label(M.risk.score(after))};}
  function downloadVerificationReport(selected){const report=M.reportPdf.make(reportData(current.name,selected));U.download(new Blob([report],{type:'application/pdf'}),'MetadataStudio_Verification_Report.pdf');}
  function downloadEvidence(cleanName,selected){const report=M.reportPdf.make(reportData(cleanName,selected));const zip=M.createZip([{name:cleanName,bytes:cleanBytes},{name:'MetadataStudio_Report.pdf',bytes:report}]);const stamp=new Date().toISOString().replace(/[-:]/g,'').replace('T','_').slice(0,13);U.download(new Blob([zip],{type:'application/zip'}),`MetadataStudio_${stamp}.zip`);}
  function reset(){current=null;originalBytes=null;engine=null;findings=[];cleanBytes=null;afterFindings=[];originalHash=cleanHash='';els.input.value='';els.status.textContent='Esperando archivo';els.status.className='status-badge neutral';els.groups.innerHTML='<div class="placeholder-state">Los hallazgos aparecerán aquí.</div>';els.list.innerHTML='';els.found.textContent=els.selected.textContent=els.preserved.textContent='0';els.score.textContent='0';els.level.textContent='Ninguno';els.ring.style.setProperty('--score',0);els.riskText.textContent='Selecciona un archivo para comenzar.';els.fingerprint.innerHTML='<b>Huella del archivo</b><span>Sin datos todavía</span>';els.clean.disabled=true;els.clean.innerHTML='<span>✣</span><span><strong>Sanear archivo</strong><small>Crear una copia limpia</small></span>';els.review.disabled=true;els.downloadClean.hidden=false;els.reset.hidden=true;els.verification.hidden=true;closeDrawer();}
  const formatsModal=$('formatsModal'),formatsBtn=$('formatsBtn'),formatsFooterBtn=$('formatsFooterBtn'),formatsClose=$('formatsClose');
  function openFormats(){formatsModal.hidden=false;document.body.style.overflow='hidden';}
  function closeFormats(){formatsModal.hidden=true;document.body.style.overflow='';}
  formatsBtn.onclick=openFormats;formatsFooterBtn.onclick=openFormats;formatsClose.onclick=closeFormats;formatsModal.onclick=e=>{if(e.target===formatsModal)closeFormats()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!formatsModal.hidden)closeFormats()});
  els.select.onclick=()=>els.input.click();els.input.onchange=e=>e.target.files[0]&&load(e.target.files[0]);els.clean.onclick=clean;els.review.onclick=openDrawer;els.details.onclick=()=>{activeCategory='resumen';activateTab('resumen');openDrawer()};els.drawerClose.onclick=closeDrawer;els.backdrop.onclick=closeDrawer;els.reset.onclick=reset;els.all.onclick=()=>{els.list.querySelectorAll('input').forEach(x=>x.checked=true);els.profile.value='custom';syncSummary();renderGroups()};els.recommended.onclick=applyProfile;els.profile.onchange=applyProfile;els.tabs.querySelectorAll('.category-tab').forEach(b=>b.onclick=()=>{activateTab(b.dataset.category);if(current)openDrawer()});['dragenter','dragover'].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.remove('drag')}));els.drop.addEventListener('drop',e=>e.dataTransfer.files[0]&&load(e.dataTransfer.files[0]));
})();
