(function(){
  const M=window.MetaStudio,U=M.utils;
  function synchsafe(b,o){return ((b[o]&0x7f)<<21)|((b[o+1]&0x7f)<<14)|((b[o+2]&0x7f)<<7)|(b[o+3]&0x7f)}
  function be32(b,o){return ((b[o]<<24)>>>0)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3]}
  function mp3(bytes){const f=[];let audioStart=0;if(U.text(bytes.subarray(0,3))==='ID3'&&bytes.length>=10){const ver=bytes[3],size=synchsafe(bytes,6),end=Math.min(bytes.length,10+size);audioStart=end;let p=10;const map={TIT2:'Título',TPE1:'Artista',TALB:'Álbum',TYER:'Año',TDRC:'Fecha',TCOM:'Compositor',TCOP:'Copyright',TENC:'Codificador',COMM:'Comentario',WXXX:'URL',APIC:'Carátula'};while(p+10<=end){const id=U.text(bytes.subarray(p,p+4));if(!/^[A-Z0-9]{4}$/.test(id))break;const len=ver>=4?synchsafe(bytes,p+4):be32(bytes,p+4);if(len<=0||p+10+len>end)break;if(map[id]){let v=id==='APIC'?`${len} bytes`:U.text(bytes.subarray(p+11,p+10+len)).replace(/\0/g,' ').trim().slice(0,180);if(v)f.push(U.finding(map[id],v,'Multimedia',true,{source:`ID3v2.${ver}`,risk:/comment|url/i.test(map[id])?'medio':'bajo'}));}p+=10+len;}f.push(U.finding('Bloque ID3v2',`${size} bytes`,'Ocultos',true,{source:`ID3v2.${ver}`,risk:'medio'}));}
    if(bytes.length>=128&&U.text(bytes.subarray(bytes.length-128,bytes.length-125))==='TAG')f.push(U.finding('ID3v1','Etiqueta de 128 bytes al final del archivo','Ocultos',true,{source:'ID3v1',risk:'medio'}));
    const tail=U.bytesToLatin1(bytes.subarray(Math.max(audioStart,bytes.length-160*1024)));if(tail.includes('APETAGEX'))f.push(U.finding('APEv2','Etiqueta APEv2 detectada en la cola','Ocultos',true,{source:'APEv2',risk:'medio'}));if(/LYRICSBEGIN|LYRICS200|LYRICSEND/.test(tail))f.push(U.finding('Lyrics3','Bloque Lyrics3 detectado','Ocultos',true,{source:'Lyrics3',risk:'medio'}));return f;}
  function cleanMp3(bytes,selected){let start=0,end=bytes.length;if(selected.some(f=>/^ID3v2/.test(f.source)||f.key==='Bloque ID3v2')&&U.text(bytes.subarray(0,3))==='ID3')start=Math.min(bytes.length,10+synchsafe(bytes,6));if(selected.some(f=>f.source==='ID3v1'||f.key==='ID3v1')&&end-start>=128&&U.text(bytes.subarray(end-128,end-125))==='TAG')end-=128;let out=bytes.subarray(start,end);if(selected.some(f=>['APEv2','Lyrics3'].includes(f.source))){let s=U.bytesToLatin1(out),cut=s.lastIndexOf('APETAGEX');const l=Math.max(s.lastIndexOf('LYRICSBEGIN'),s.lastIndexOf('LYRICS200'));if(l>=0&&(cut<0||l<cut))cut=l;if(cut>=0)out=out.subarray(0,cut);}return out.slice();}
  function inspectTextWindow(bytes,start,len){return U.bytesToLatin1(bytes.subarray(start,Math.min(bytes.length,start+len)));}
  function mp4(bytes){const f=[],win=12*1024*1024,head=inspectTextWindow(bytes,0,win),tail=bytes.length>win?inspectTextWindow(bytes,Math.max(0,bytes.length-win),win):'',s=head+' '+tail;const tags=[['©nam','Título'],['©ART','Autor/Artista'],['©alb','Álbum'],['©too','Codificador'],['©day','Fecha'],['com.apple.quicktime.location.ISO6709','Ubicación'],['com.apple.quicktime.make','Fabricante del dispositivo'],['com.apple.quicktime.model','Modelo del dispositivo'],['com.apple.quicktime.software','Software']];for(const[needle,label]of tags){const i=s.indexOf(needle);if(i>=0){const val=s.slice(i+needle.length,i+needle.length+180).replace(/[^\x20-\x7e]/g,' ').replace(/\s+/g,' ').trim();f.push(U.finding(label,val||'Detectado',/location/i.test(needle)?'Ubicación':/make|model/i.test(needle)?'Dispositivo':'Multimedia',true,{source:'MP4/MOV atom',risk:/location/i.test(needle)?'critico':'medio'}));}}f.push(U.finding('Cobertura multimedia','Inspección de cabecera y cola; este formato no dispone de saneamiento binario completo.','Multimedia',false,{source:'Motor multimedia',risk:'info',kind:'coverage'}));return f;}
  function wav(bytes){const f=[];if(U.text(bytes.subarray(0,4))!=='RIFF')return f;let p=12;while(p+8<=bytes.length){const id=U.text(bytes.subarray(p,p+4)),len=new DataView(bytes.buffer,bytes.byteOffset+p+4,4).getUint32(0,true);if(['LIST','INFO','bext','iXML','ID3 '].includes(id))f.push(U.finding(`Chunk ${id}`,`${len} bytes`,'Multimedia',true,{source:'WAV',risk:'medio'}));if(len<0||p+8+len>bytes.length)break;p+=8+len+(len%2);}return f;}
  M.media={supports(ext){return ['mp3','mp4','mov','m4a','wav','flac','ogg','webm','mkv','avi'].includes(ext);},async analyze(bytes,file){const ext=U.ext(file?.name||'');if(ext==='mp3')return mp3(bytes);if(['mp4','mov','m4a'].includes(ext))return mp4(bytes);if(ext==='wav')return wav(bytes);const win=2*1024*1024,head=inspectTextWindow(bytes,0,win),tail=bytes.length>win?inspectTextWindow(bytes,Math.max(0,bytes.length-win),win):'',s=head+' '+tail,f=[];for(const[re,label]of[[/ENCODER=([^\0\r\n]+)/i,'Codificador'],[/TITLE=([^\0\r\n]+)/i,'Título'],[/ARTIST=([^\0\r\n]+)/i,'Artista'],[/COMMENT=([^\0\r\n]+)/i,'Comentario']]){const m=re.exec(s);if(m)f.push(U.finding(label,m[1].slice(0,160),'Multimedia',true,{source:ext.toUpperCase(),risk:'medio'}));}f.push(U.finding('Cobertura multimedia','Inspección parcial de cabecera y cola; sin saneador completo para este formato.','Multimedia',false,{source:ext.toUpperCase(),risk:'info',kind:'coverage'}));return f;},async clean(bytes,selected,file){const ext=U.ext(file?.name||'');if(ext==='mp3')return cleanMp3(bytes,selected);throw new Error('Este formato multimedia admite inspección parcial, pero no saneamiento binario seguro en esta versión.');}};
})();
