(function(){
  const M=window.MetaStudio,U=M.utils;
  function synchsafe(b,o){return ((b[o]&0x7f)<<21)|((b[o+1]&0x7f)<<14)|((b[o+2]&0x7f)<<7)|(b[o+3]&0x7f)}
  function mp3(bytes){const f=[];if(U.text(bytes.subarray(0,3))!=='ID3')return f;const size=synchsafe(bytes,6),end=Math.min(bytes.length,10+size);let p=10;const map={TIT2:'Título',TPE1:'Artista',TALB:'Álbum',TYER:'Año',TDRC:'Fecha',TCOM:'Compositor',TCOP:'Copyright',TENC:'Codificador',COMM:'Comentario',WXXX:'URL',APIC:'Carátula'};while(p+10<=end){const id=U.text(bytes.subarray(p,p+4));if(!/^[A-Z0-9]{4}$/.test(id))break;const len=(bytes[p+4]<<24)|(bytes[p+5]<<16)|(bytes[p+6]<<8)|bytes[p+7];if(len<=0||p+10+len>end)break;if(map[id]){let v=id==='APIC'?`${len} bytes`:U.text(bytes.subarray(p+11,p+10+len)).replace(/\0/g,' ').trim().slice(0,180);if(v)f.push(U.finding(map[id],v,'Multimedia',true,{source:'ID3',risk:/comment|url/i.test(map[id])?'medio':'bajo'}));}p+=10+len;}f.push(U.finding('Bloque ID3',`${size} bytes`,'Ocultos',true,{source:'ID3',risk:'medio'}));return f;}
  function cleanMp3(bytes,selected){if(U.text(bytes.subarray(0,3))!=='ID3')return bytes.slice();if(!selected.some(f=>f.source==='ID3'||f.key==='Bloque ID3'))return bytes.slice();const size=synchsafe(bytes,6);return bytes.subarray(Math.min(bytes.length,10+size)).slice();}
  function mp4(bytes){const f=[];const s=U.bytesToLatin1(bytes.subarray(0,Math.min(bytes.length,12*1024*1024)));const tags=[['©nam','Título'],['©ART','Autor/Artista'],['©alb','Álbum'],['©too','Codificador'],['©day','Fecha'],['com.apple.quicktime.location.ISO6709','Ubicación'],['com.apple.quicktime.make','Fabricante del dispositivo'],['com.apple.quicktime.model','Modelo del dispositivo'],['com.apple.quicktime.software','Software']];for(const [needle,label] of tags){const i=s.indexOf(needle);if(i>=0){const val=s.slice(i+needle.length,i+needle.length+180).replace(/[^\x20-\x7e]/g,' ').replace(/\s+/g,' ').trim();f.push(U.finding(label,val||'Detectado',/location/i.test(needle)?'Ubicación':/make|model/i.test(needle)?'Dispositivo':'Multimedia',true,{source:'MP4/MOV atom',risk:/location/i.test(needle)?'critico':'medio'}));}}if(/encoder|writing application/i.test(s))f.push(U.finding('Codificador','Detectado','Software',true,{source:'MP4/MOV'}));return f;}
  function wav(bytes){const f=[];if(U.text(bytes.subarray(0,4))!=='RIFF')return f;let p=12;while(p+8<=bytes.length){const id=U.text(bytes.subarray(p,p+4)),len=new DataView(bytes.buffer,bytes.byteOffset+p+4,4).getUint32(0,true);if(['LIST','INFO','bext','iXML','ID3 '].includes(id))f.push(U.finding(`Chunk ${id}`,`${len} bytes`,'Multimedia',true,{source:'WAV',risk:'medio'}));p+=8+len+(len%2);}return f;}
  M.media={supports(ext){return ['mp3','mp4','mov','m4a','wav','flac','ogg','webm','mkv','avi'].includes(ext);},async analyze(bytes,file){const ext=U.ext(file?.name||'');if(ext==='mp3')return mp3(bytes);if(['mp4','mov','m4a'].includes(ext))return mp4(bytes);if(ext==='wav')return wav(bytes);const head=U.bytesToLatin1(bytes.subarray(0,Math.min(bytes.length,2*1024*1024)));const f=[];for(const [re,label] of [[/ENCODER=([^\0\r\n]+)/i,'Codificador'],[/TITLE=([^\0\r\n]+)/i,'Título'],[/ARTIST=([^\0\r\n]+)/i,'Artista'],[/COMMENT=([^\0\r\n]+)/i,'Comentario']]){const m=re.exec(head);if(m)f.push(U.finding(label,m[1].slice(0,160),'Multimedia',true,{source:ext.toUpperCase(),risk:'medio'}));}return f;},async clean(bytes,selected,file){const ext=U.ext(file?.name||'');if(ext==='mp3')return cleanMp3(bytes,selected);throw new Error('Este formato multimedia admite inspección, pero todavía no saneamiento binario seguro en esta versión.');}};
})();
