(function(){
  const M=window.MetaStudio,U=M.utils,S=M.security;
  function xmlText(b,path){if(!b)return'';if(b.length>S.MAX_OOXML_PROPS_XML)throw new Error(`${path} supera el límite seguro de ${U.humanSize(S.MAX_OOXML_PROPS_XML)}.`);return U.text(b);}
  function capture(xml,tag){const open=new RegExp('<([A-Za-z_][\\w.-]*:)?'+tag+'(?:\\s[^>]{0,512})?>','i').exec(xml);if(!open)return'';const prefix=open[1]||'',start=open.index+open[0].length,end=xml.indexOf(`</${prefix}${tag}>`,start);if(end<0)return'';return xml.slice(start,end).replace(/<[^>]{0,2048}>/g,'').trim();}
  function setBlank(xml,tag){const re=new RegExp('(<(?:\\w+:)?'+tag+'(?:\\s[^>]{0,512})?>)([\\s\\S]*?)(<\\/(?:\\w+:)?'+tag+'>)','gi');return xml.replace(re,'$1$3');}
  const coreMap=[['creator','Author'],['lastModifiedBy','Last modified by'],['title','Title'],['subject','Subject'],['keywords','Keywords'],['description','Description'],['category','Category'],['contentStatus','Content status'],['created','Created'],['modified','Modified'],['lastPrinted','Last printed']];
  const appMap=[['Company','Company'],['Manager','Manager'],['Application','Application'],['AppVersion','Application version']];
  function attrFindings(xml,path){const out=[];for(const m of xml.matchAll(/\bw:author="([^"]+)"/gi)){const v=m[1].trim();if(v)out.push(U.finding('Autor de revisión',v,'Identidad',false,{source:'OOXML revisión',risk:'alto',path}));}for(const m of xml.matchAll(/\bw:date="([^"]+)"/gi)){const v=m[1].trim();if(v)out.push(U.finding('Fecha de revisión',v,'Fechas',false,{source:'OOXML revisión',risk:'medio',path}));}return out;}
  async function detectExtra(z,ext,f){
    const entries=z.entries.map(e=>e.name);
    for(const name of entries){
      if(/(?:^|\/)comments(?:Extended)?\.xml$/i.test(name)||/(?:^|\/)people\.xml$/i.test(name))f.push(U.finding('Comentarios / personas','Estructura de colaboración detectada','Ocultos',false,{source:'OOXML colaboración',risk:'alto',path:name}));
      if(/^docProps\/thumbnail\./i.test(name))f.push(U.finding('Miniatura del documento',name,'Ocultos',false,{source:'OOXML thumbnail',risk:'medio',path:name}));
      if(/printerSettings.*\.bin$/i.test(name))f.push(U.finding('Configuración de impresora',name,'Software',false,{source:'OOXML printerSettings',risk:'alto',path:name}));
      if(/^customXml\//i.test(name))f.push(U.finding('Custom XML',name,'Ocultos',false,{source:'OOXML customXml',risk:'medio',path:name}));
    }
    const candidates=entries.filter(n=>/^(word\/document\.xml|word\/comments.*\.xml|word\/people\.xml)$/i.test(n));
    for(const path of candidates){const b=await z.read(path);if(!b)continue;if(b.length>8*1024*1024){f.push(U.finding('Contenido OOXML grande',`${path}: ${U.humanSize(b.length)}`,'Documento',false,{source:'OOXML',risk:'info',path,kind:'coverage'}));continue;}f.push(...attrFindings(U.text(b),path));}
    const rels=entries.filter(n=>/_rels\/.*\.rels$/i.test(n));for(const path of rels.slice(0,200)){const b=await z.read(path);if(!b||b.length>1024*1024)continue;const xml=U.text(b);for(const m of xml.matchAll(/Target="(file:\/{2,3}[^"<>]+|[A-Za-z]:\\[^"<>]+)"/gi))f.push(U.finding('Ruta local relacionada',m[1],'Identidad',false,{source:'OOXML relationship',risk:'alto',path}));}
    f.push(U.finding('Cobertura OOXML','Se inspeccionan propiedades, revisiones/comentarios, miniaturas, printerSettings, relaciones locales y estructuras conocidas; no se modifica contenido editorial ni firmas.','Documento',false,{source:'Motor OOXML',risk:'info',kind:'coverage'}));
  }
  M.ooxml={supports(ext){return ['docx','xlsx','pptx'].includes(ext);},async analyze(bytes,file){const z=new M.ZipLite(bytes),f=[];for(const[path,map,cat]of[['docProps/core.xml',coreMap,'Office core'],['docProps/app.xml',appMap,'Office app']]){const b=await z.read(path);if(!b)continue;const xml=xmlText(b,path);for(const[tag,label]of map){const v=capture(xml,tag);if(v)f.push(U.finding(label,v,cat,true,{source:cat,path}));}}const custom=await z.read('docProps/custom.xml');if(custom){const xml=xmlText(custom,'docProps/custom.xml'),props=[...xml.matchAll(/<property\b[^>]{0,1024}name="([^"]+)"[^>]*>[\s\S]*?<\/property>/gi)];for(const p of props)f.push(U.finding(`Custom: ${p[1]}`,'Detectado','Office custom',true,{source:'Office custom',path:'docProps/custom.xml'}));}await detectExtra(z,U.ext(file?.name||''),f);return f;},async clean(bytes,selected){const z=new M.ZipLite(bytes),keys=new Set(selected.map(x=>x.key)),cats=new Set(selected.map(x=>x.category));let b=await z.read('docProps/core.xml');if(b){let xml=xmlText(b,'docProps/core.xml');for(const[tag,label]of coreMap)if(keys.has(label))xml=setBlank(xml,tag);z.set('docProps/core.xml',U.utf8(xml));}b=await z.read('docProps/app.xml');if(b){let xml=xmlText(b,'docProps/app.xml');for(const[tag,label]of appMap)if(keys.has(label))xml=setBlank(xml,tag);z.set('docProps/app.xml',U.utf8(xml));}b=await z.read('docProps/custom.xml');if(b&&cats.has('Office custom')){let xml=xmlText(b,'docProps/custom.xml');xml=xml.replace(/<property\b[^>]{0,1024}>[\s\S]*?<\/property>/gi,'');z.set('docProps/custom.xml',U.utf8(xml));}return z.build();}};
})();
