(function(){
  const M=window.MetaStudio,U=M.utils;
  const fields=['Title','Author','Subject','Keywords','Creator','Producer','CreationDate','ModDate'];
  function normalizeValue(v){return String(v||'').replace(/\u0000/g,'').replace(/[\u0001-\u001F\u007F]/g,'').trim();}
  function decodePdfString(token){if(!token)return'';if(token[0]==='('){const raw=token.slice(1,-1).replace(/\\([()\\])/g,'$1').replace(/\\([0-7]{1,3})/g,(m,o)=>String.fromCharCode(parseInt(o,8)));return normalizeValue(raw).slice(0,220);}if(token[0]==='<'){const h=token.slice(1,-1).replace(/\s/g,'');if(!h||/^0+$/.test(h))return'';if(h.startsWith('FEFF')){let out='';for(let i=4;i+3<h.length;i+=4)out+=String.fromCharCode(parseInt(h.slice(i,i+4),16));return normalizeValue(out).slice(0,220);}let raw='';for(let i=0;i+1<h.length;i+=2)raw+=String.fromCharCode(parseInt(h.slice(i,i+2),16));const cleaned=normalizeValue(raw);return cleaned?cleaned.slice(0,220):'';}return normalizeValue(token);}
  function findInfo(s){const f=[];for(const k of fields){const re=new RegExp('\\/'+k+'\\s*(\\((?:\\\\.|[^\\\\)])*\\)|<[^>]*>)','g');let m;while((m=re.exec(s))){const v=normalizeValue(decodePdfString(m[1]));if(v)f.push(U.finding(k,v,'PDF info',true));if(f.filter(x=>x.key===k).length>0)break;}}if(/<x:xmpmeta|<rdf:RDF|xpacket begin/i.test(s))f.push(U.finding('XMP metadata','Detected','XMP',true));return f;}
  function blankToken(t){if(t[0]==='(')return '('+' '.repeat(Math.max(0,t.length-2))+')';if(t[0]==='<')return '<'+'0'.repeat(Math.max(0,t.length-2))+'>';return t;}
  function scrubXmp(s){const tags=['dc:title','dc:creator','dc:description','dc:subject','pdf:Keywords','pdf:Producer','xmp:CreatorTool','xmp:CreateDate','xmp:ModifyDate','xmp:MetadataDate'];for(const tag of tags){const re=new RegExp('(<'+tag+'(?:\\s[^>]*)?>)([\\s\\S]*?)(<\\/'+tag+'>)','gi');s=s.replace(re,(m,a,b,c)=>a+b.replace(/[^<>\r\n]/g,' ')+c);}return s;}
  M.pdf={supports(ext){return ext==='pdf';},async analyze(bytes){return findInfo(U.bytesToLatin1(bytes));},async clean(bytes,selected){let s=U.bytesToLatin1(bytes);const keys=new Set(selected.map(x=>x.key)),cats=new Set(selected.map(x=>x.category));for(const k of fields){if(!keys.has(k))continue;const re=new RegExp('(\\/'+k+'\\s*)(\\((?:\\\\.|[^\\\\)])*\\)|<[^>]*>)','g');s=s.replace(re,(m,a,b)=>a+blankToken(b));}if(cats.has('XMP'))s=scrubXmp(s);return U.latin1ToBytes(s);}};
})();
