(function(){
  const M=window.MetaStudio,U=M.utils,S=M.security;
  const fields=['Title','Author','Subject','Keywords','Creator','Producer','CreationDate','ModDate'];
  function normalizeValue(v){return String(v||'').replace(/\u0000/g,'').replace(/[\u0001-\u001F\u007F]/g,'').trim();}
  function decodePdfString(token){if(!token)return'';if(token[0]==='('){const raw=token.slice(1,-1).replace(/\\([()\\])/g,'$1').replace(/\\([0-7]{1,3})/g,(m,o)=>String.fromCharCode(parseInt(o,8)));return normalizeValue(raw).slice(0,220);}if(token[0]==='<'){const h=token.slice(1,-1).replace(/\s/g,'');if(!h||/^0+$/.test(h))return'';if(/^FEFF/i.test(h)){let out='';for(let i=4;i+3<h.length;i+=4)out+=String.fromCharCode(parseInt(h.slice(i,i+4),16));return normalizeValue(out).slice(0,220);}let raw='';for(let i=0;i+1<h.length;i+=2)raw+=String.fromCharCode(parseInt(h.slice(i,i+2),16));return normalizeValue(raw).slice(0,220);}return normalizeValue(token);}
  function parseObjects(s){const out=new Map(),re=/(\d+)\s+(\d+)\s+obj\b/g;let m;while((m=re.exec(s))){const bodyStart=re.lastIndex,end=s.indexOf('endobj',bodyStart);if(end<0)break;out.set(`${m[1]} ${m[2]}`,{num:+m[1],gen:+m[2],bodyStart,bodyEnd:end,body:s.slice(bodyStart,end)});re.lastIndex=end+6;}return out;}
  function supportCheck(s){if(!s.startsWith('%PDF-'))throw new Error('PDF no válido: firma %PDF- ausente.');const eof=(s.match(/%%EOF/g)||[]).length;if(eof!==1)throw new Error('PDF complejo no soportado de forma segura: contiene actualizaciones incrementales o múltiples EOF.');if(/\/Encrypt\b/.test(s))throw new Error('PDF cifrado no soportado para saneamiento local.');if(/\/Type\s*\/ObjStm\b/.test(s))throw new Error('PDF complejo no soportado: contiene Object Streams.');if(/\/Type\s*\/XRef\b/.test(s))throw new Error('PDF complejo no soportado: utiliza XRef streams.');if(!/\bstartxref\b/.test(s)||!/\btrailer\b/.test(s))throw new Error('PDF no compatible: estructura xref/trailer no reconocida.');const objects=parseObjects(s);for(const o of objects.values()){if(/\/(?:Type\s*\/Metadata|Subtype\s*\/XML)\b/.test(o.body)&&/\/Filter\b/.test(o.body))throw new Error('PDF complejo no soportado: metadatos XMP comprimidos.');}return objects;}
  function trailerInfoRef(s){const ti=s.lastIndexOf('trailer'),end=s.indexOf('startxref',ti);if(ti<0)return null;const t=s.slice(ti,end>ti?end:s.length),m=/\/Info\s+(\d+)\s+(\d+)\s+R/.exec(t);return m?`${m[1]} ${m[2]}`:null;}
  function extractInfo(body){const f=[];for(const k of fields){const re=new RegExp('\\/'+k+'\\s*(\\((?:\\\\.|[^\\\\)])*\\)|<[^>]*>)','g'),m=re.exec(body||'');if(m){const v=decodePdfString(m[1]);if(v)f.push(U.finding(k,v,'PDF info',true,{source:'PDF Info Dictionary'}));}}return f;}
  function metadataStreams(s,objects){const a=[];for(const o of objects.values()){if(!/\/(?:Type\s*\/Metadata|Subtype\s*\/XML)\b/.test(o.body))continue;const si=o.body.indexOf('stream');if(si<0)continue;let cs=si+6;if(o.body.slice(cs,cs+2)==='\r\n')cs+=2;else if(/[\r\n]/.test(o.body[cs]||''))cs+=1;const ei=o.body.indexOf('endstream',cs);if(ei<0)throw new Error('PDF no compatible: stream de metadatos truncado.');a.push({start:o.bodyStart+cs,end:o.bodyStart+ei,content:o.body.slice(cs,ei)});}return a;}
  function blankToken(t){if(t[0]==='(')return '('+' '.repeat(Math.max(0,t.length-2))+')';if(t[0]==='<')return '<'+'0'.repeat(Math.max(0,t.length-2))+'>';return t;}
  M.pdf={supports(ext){return ext==='pdf';},async analyze(bytes){S.assertSignature(bytes,{name:'x.pdf'});const s=U.bytesToLatin1(bytes),objects=supportCheck(s),f=[],ref=trailerInfoRef(s);if(ref&&objects.has(ref))f.push(...extractInfo(objects.get(ref).body));const streams=metadataStreams(s,objects);if(streams.some(x=>normalizeValue(x.content)))f.push(U.finding('XMP metadata','Paquete XMP/XML detectado','XMP',true,{source:'PDF Metadata stream'}));return f;},async clean(bytes,selected){let s=U.bytesToLatin1(bytes),objects=supportCheck(s),keys=new Set(selected.map(x=>x.key)),cats=new Set(selected.map(x=>x.category)),ref=trailerInfoRef(s);if(ref&&objects.has(ref)){const o=objects.get(ref);let body=o.body;for(const k of fields){if(!keys.has(k))continue;const re=new RegExp('(\\/'+k+'\\s*)(\\((?:\\\\.|[^\\\\)])*\\)|<[^>]*>)','g');body=body.replace(re,(m,a,b)=>a+blankToken(b));}if(body.length!==o.body.length)throw new Error('Saneamiento PDF abortado: cambio estructural inesperado.');s=s.slice(0,o.bodyStart)+body+s.slice(o.bodyEnd);objects=parseObjects(s);}if(cats.has('XMP')||keys.has('XMP metadata')){const streams=metadataStreams(s,objects).sort((a,b)=>b.start-a.start);for(const st of streams){const blank=' '.repeat(st.end-st.start);s=s.slice(0,st.start)+blank+s.slice(st.end);}}const out=U.latin1ToBytes(s);if(out.length!==bytes.length)throw new Error('Saneamiento PDF abortado: el tamaño estructural cambió.');return out;}};
})();
